---
new_page_extension: md
auto_deploy: true
admin_path: ".forestry"
webhook_url: 
sections:
- type: directory
  path: _cases
  label: Кейсы
  create: all
  match: "**/*"
- type: jekyll-pages
  label: Разделы
  create: all
- type: directory
  path: _data/testimonials
  label: Отзывы
  create: all
  match: "**/*"
upload_dir: assets/uploads
public_path: "../assets/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
